CREATE TABLE USER_DETAILS(
    EMP_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    FIRST_NAME VARCHAR(30) NOT NULL,
    MIDDLE_NAME VARCHAR(20),
    LAST_NAME VARCHAR(30) NOT NULL,
    DOB DATE NOT NULL,
    GENDER VARCHAR(10) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    CONTACT_NO BIGINT NOT NULL,
    DEPT_ID INT NOT NULL,
    DESIGNATION VARCHAR(30) NOT NULL,
    SALARY BIGINT,
    DOJ DATE,
    FOREIGN KEY(DEPT_ID) REFERENCES DEPARTMENT(DEPT_ID)
);

CREATE TABLE DEPARTMENT(
    DEPT_ID INT PRIMARY KEY NOT NULL AUTO_INCREMENT,
    DEPT_NAME VARCHAR(30),
);